name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Désactiver l'authentification persistante

      # Supprimer manuellement le .extraheader si nécessaire
      - name: Remove extraheader
        run: git config --unset-all http.https://github.com/.extraheader || true

      # Étape pour obtenir la date
      - name: Get Date
        id: get-date
        run: |
          echo "DATE=$(date -u '+%Y%m%d')" >> $GITHUB_ENV

      # Étape pour mettre en cache le répertoire global de Buildozer
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Étape pour construire avec Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug

      # Étape pour uploader les artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
