name: CI  # Nom du workflow

on:  # Déclencheurs
  push:
    branches: [ main ]  # Le workflow se déclenche sur les pushs à la branche principale

jobs:  # Les tâches à exécuter
  build:  # Nom de la tâche
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu

    steps:  # Les étapes à exécuter
      - name: Checkout repository  # Étape pour cloner le dépôt
        uses: actions/checkout@v3  # Utilise l'action pour cloner
        with:
          persist-credentials: false  # Empêche l'ajout d'informations d'identification persistantes

      - name: Remove extraheader  # Supprimer une configuration Git non désirée
        run: git config --unset-all http.https://github.com/.extraheader || true

      - name: Get Date  # Obtenir la date actuelle
        id: get-date
        run: echo "DATE=$(date -u '+%Y%m%d')" >> $GITHUB_ENV  # Stocke la date dans une variable d'environnement

      - name: Cache Buildozer global directory  # Mettre en cache les dépendances
        uses: actions/cache@v3
        with:
          path: .buildozer_global  # Chemin du cache
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}  # Clé de cache basée sur le fichier buildozer.spec

      - name: Build with Buildozer  # Construire l'application Android
        uses: ArtemSBulgakov/buildozer-action@v1  # Utilise l'action Buildozer
        id: buildozer
        with:
          command: buildozer android debug  # Commande de construction

      - name: Upload artifacts  # Uploader les fichiers générés
        uses: actions/upload-artifact@v3  # Utilise l'action d'upload
        with:
          name: package  # Nom des artefacts
          path: ${{ steps.buildozer.outputs.filename }}  # Chemin vers le fichier à uploader
